server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      pattern: '%{yyyy-MM-dd}tT%{HH:mm:ss.SSSZ}t %a "%r" %s (%D ms)'
    basedir: /tmp/tomcat/fitness-tracker # This is relative to where the directory of the whole project is found

spring:
  application:
    name: fitness-tracker
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true

  flyway:
    enabled: true
    locations:
      - classpath:db/migration/{vendor}
    out-of-order: true
    ignore-missing-migrations: true

  h2:
    console:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver

logging:
  file:
    name: /tmp/fitness-tracker/spring-reactive.log
  level:
    root: INFO
    com:
      pet: DEBUG
