server:
  port: 8080

spring:
  application:
    name: fitness-tracker
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true

  flyway:
    enabled: true
    locations:
      - classpath:db/migration/{vendor}
    out-of-order: true
    ignore-missing-migrations: true

  h2:
    console:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver

logging:
  file: /tmp/fitness-tracker/spring-reactive.log
  level:
    root: INFO
